name: Flutter Build for Windows

on:
  push:
    branches:
      - main  # L'action se déclenche sur un push vers la branche 'main'
  pull_request:
    branches:
      - main  # L'action se déclenche aussi sur un pull request vers 'main'

jobs:
  build:
    runs-on: windows-latest  # Utilisation d'un runner Windows
    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Utilisation de la version stable de Flutter

      # Installer les dépendances
      - name: Install dependencies
        run: flutter pub get

      # Exécuter la commande pour générer la build Windows
      - name: Build Windows
        run: flutter build windows --release  # Compilation en mode release pour Windows

      # Télécharger les artefacts de la build
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build  # Nom de l'artefact
          path: build/windows/runner/Release/  # Le chemin où la build Windows sera générée
