name: Flutter Build for Windows

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release  

      - name: List build directory (debugging)
        run: Get-ChildItem -Recurse build/windows | Format-Table -AutoSize

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4  
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/
